---
- hosts: all
  become: yes
  gather_facts: yes

  vars:
    placeholder: 123

  tasks:
    # zsh installation steps taken and adapted from
    # https://shaunandersonaz.github.io/Ansible-To-Setup-OhMyZSH-and-PowerLevel10K/
    - name: Install zsh
      ansible.builtin.package:
        name: zsh
        state: present
      become: true

    - name: Set user shell to zsh
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh
      become: true

    - name: Download ohmyzsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/home/{{ user }}/install.sh"
        mode: '0755'

    - name: Install ohmyzsh
      ansible.builtin.script:
        cmd: "/home/{{ user }}/install.sh"

    - name: Install PowerLevel10K
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: Download NerdFonts
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Meslo.zip
        dest: "/home/{{ user }}/Meslo.zip"

    - name: Create temp directory
      ansible.builtin.file:
        path: "/home/{{ user }}/Meslo"
        state: directory
        mode: '0755'

    - name: Install font files
      ansible.builtin.unarchive:
        src: "/home/{{ user }}/Meslo.zip"
        dest: "/home/{{ user }}/Meslo"

    - name: Move font files to fonts directory
      ansible.builtin.copy:
        src: "/home/{{ user }}/Meslo"
        dest: /usr/share/fonts/Meslo
        owner: root
      become: true

    - name: Update .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.zshrc"
        insertafter: EOF
        line: "source /home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme"

    # Install base utilities
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present
      become: true

    - name: Install vim
      ansible.builtin.package:
        name: vim
        state: present
      become: true

    - name: Set EDITOR environmental variable to vim
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.zshrc"
        line: 'export EDITOR=vim'
        create: true
        insertafter: EOF
        state: present

    - name: Install fzf
      ansible.builtin.package:
        name: fzf
        state: present
      become: true

    - name: Install bat
      ansible.builtin.package:
        name: bat
        state: present
      become: true

    - name: Install mosh
      ansible.builtin.package:
        name: mosh
        state: present
      become: true

    # Install tmux
    - name: Install tmux
      ansible.builtin.package:
        name: tmux
        state: present
      become: true

    - name: Install Oh my tmux
      ansible.builtin.shell: 'curl -fsSL "https://github.com/gpakosz/.tmux/raw/refs/heads/master/install.sh#$(date +%s)" | bash'
      args:
        executable: /bin/bash
        creates: "/home/{{ user }}/.tmux"
      become: true
      become_user: "{{ user }}"
      environment:
        HOME: "/home/{{ user }}"

    # Install mise
    - name: Download mise installer script
      ansible.builtin.get_url:
        url: https://mise.run
        dest: /tmp/install_mise.sh
        mode: '0755'

    - name: Run mise installer script
      ansible.builtin.shell: /tmp/install_mise.sh

    - name: Add mise activations to runtime config
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.zshrc"
        line: 'eval "$(/home/{{ user }}/.local/bin/mise activate zsh)"'
        create: true
        insertafter: EOF
        state: present

    # Install Python
    - name: Install Python Latest
      ansible.builtin.shell: 'mise install python@latest'

    - name: Set global Python version
      ansible.builtin.shell: 'mise use -g python@latest'

    # Install pytap2, which the Meshtastic CLI depends on.
    - name: Install pytap2
      ansible.builtin.shell: 'pip install --upgrade pytap2'

    # Install Meshtastic CLI
    - name: Install Meshtastic CLI
      ansible.builtin.shell: 'pip install --upgrade meshtastic[cli]'

    # Install unattended-upgrades
    - name: Install unattended-upgrades
      ansible.builtin.package:
        name: unattended-upgrades
        state: present
      become: true

    - name: Enable unattended-upgrades
      ansible.builtin.shell: 'dpkg-reconfigure --priority=low unattended-upgrades'
      become: true

    # Install Tailscale
    - name: Install Tailscale
      ansible.builtin.shell: 'curl -fsSL https://tailscale.com/install.sh | sh'
      become: true
    # You need to run `sudo tailscale up` manually after installation.

    # Set up cron jobs
    - name: Schedule a weekly reboot of the pi
      ansible.builtin.cron:
        name: "weekly_pi_reboot"
        user: "root"
        minute: "0"
        hour: "4"
        job: "/sbin/shutdown -r now"
        state: present

    # TODO - Make the Python version path dynamic
    - name: Schedule a weekly reboot of the Meshtastic node
      ansible.builtin.cron:
        name: "weekly_node_reboot"
        user: "{{ user }}"
        minute: "30"
        hour: "4"
        job: "/home/{{ user }}/.local/share/mise/installs/python/3.14.0/bin/meshtastic --reboot"
        state: present

    - name: Schedule a daily backup of the Meshtastic node's config
      ansible.builtin.cron:
        name: "daily_node_config_backup"
        user: "{{ user }}"
        minute: "15"
        hour: "2"
        job: "/home/{{ user }}/.local/share/mise/installs/python/3.14.0/bin/python /home/{{ user }}/scripts/backup_node_config.py"
        state: present

    - name: Schedule a daily attempt to update the Meshtastic CLI
      ansible.builtin.cron:
        name: "daily_meshtastic_cli_update"
        user: "{{ user }}"
        minute: "0"
        hour: "0"
        job: '/home/{{ user }}/.local/share/mise/installs/python/3.14.0/bin/pip install --upgrade --no-cache-dir "meshtastic[cli]"'
        state: present
